version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: reiseinfo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reiseinfo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reiseinfo-network

  adminer:
    image: adminer
    container_name: reiseinfo-adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - reiseinfo-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  reiseinfo-network:
    driver: bridge